from sqlalchemy import Column, Integer, String, DateTime, ForeignKey
from sqlalchemy.orm import declarative_base, relationship
from datetime import datetime

# Base class for all models
Base = declarative_base()


# ============================================================
# USER MODEL
# ============================================================
class User(Base):
    """
    Represents a user of the system.

    One user can have many clips.
    """

    __tablename__ = "users"

    # Primary key
    id = Column(Integer, primary_key=True, index=True)

    # Authentication fields
    email = Column(String, unique=True, index=True, nullable=False)
    hashed_password = Column(String, nullable=False)

    # Authorization role
    role = Column(String, default="user", nullable=False)

    # Timestamp for account creation
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationship: one user -> many clips
    clips = relationship("Clip", back_populates="user", cascade="all, delete")


# ============================================================
# CLIP MODEL
# ============================================================
class Clip(Base):
    """
    Represents a video clip generated by the ML module.

    A clip:
    - belongs to one user
    - is stored on disk (file_path)
    """

    __tablename__ = "clips"

    # Primary key
    id = Column(Integer, primary_key=True, index=True)

    # Foreign key linking to User
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)

    # File path on disk (video file location)
    file_path = Column(String, nullable=False)

    # Timestamp when clip record is created
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationship: many clips -> one user
    user = relationship("User", back_populates="clips")